/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumSubscriptionGroupGroupType } from "./EnumSubscriptionGroupGroupType";
import { IsEnum, IsOptional, IsString, ValidateNested } from "class-validator";
import { PlanCreateNestedManyWithoutSubscriptionGroupsInput } from "./PlanCreateNestedManyWithoutSubscriptionGroupsInput";
import { Type } from "class-transformer";
import { EnumSubscriptionGroupVisibility } from "./EnumSubscriptionGroupVisibility";
@InputType()
class SubscriptionGroupCreateInput {
  @ApiProperty({
    required: false,
    enum: EnumSubscriptionGroupGroupType,
    isArray: true,
  })
  @IsEnum(EnumSubscriptionGroupGroupType, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumSubscriptionGroupGroupType], {
    nullable: true,
  })
  groupType?: Array<"Campaign" | "Standard">;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PlanCreateNestedManyWithoutSubscriptionGroupsInput,
  })
  @ValidateNested()
  @Type(() => PlanCreateNestedManyWithoutSubscriptionGroupsInput)
  @IsOptional()
  @Field(() => PlanCreateNestedManyWithoutSubscriptionGroupsInput, {
    nullable: true,
  })
  plans?: PlanCreateNestedManyWithoutSubscriptionGroupsInput;

  @ApiProperty({
    required: false,
    enum: EnumSubscriptionGroupVisibility,
    isArray: true,
  })
  @IsEnum(EnumSubscriptionGroupVisibility, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumSubscriptionGroupVisibility], {
    nullable: true,
  })
  visibility?: Array<"Private" | "Public">;
}
export { SubscriptionGroupCreateInput };
