/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateSubscriptionGroupArgs } from "./CreateSubscriptionGroupArgs";
import { UpdateSubscriptionGroupArgs } from "./UpdateSubscriptionGroupArgs";
import { DeleteSubscriptionGroupArgs } from "./DeleteSubscriptionGroupArgs";
import { SubscriptionGroupFindManyArgs } from "./SubscriptionGroupFindManyArgs";
import { SubscriptionGroupFindUniqueArgs } from "./SubscriptionGroupFindUniqueArgs";
import { SubscriptionGroup } from "./SubscriptionGroup";
import { PlanFindManyArgs } from "../../plan/base/PlanFindManyArgs";
import { Plan } from "../../plan/base/Plan";
import { SubscriptionGroupService } from "../subscriptionGroup.service";

@graphql.Resolver(() => SubscriptionGroup)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SubscriptionGroupResolverBase {
  constructor(
    protected readonly service: SubscriptionGroupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SubscriptionGroup",
    action: "read",
    possession: "any",
  })
  async _subscriptionGroupsMeta(
    @graphql.Args() args: SubscriptionGroupFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [SubscriptionGroup])
  @nestAccessControl.UseRoles({
    resource: "SubscriptionGroup",
    action: "read",
    possession: "any",
  })
  async subscriptionGroups(
    @graphql.Args() args: SubscriptionGroupFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SubscriptionGroup[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "SubscriptionGroup",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => SubscriptionGroup, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SubscriptionGroup",
    action: "read",
    possession: "own",
  })
  async subscriptionGroup(
    @graphql.Args() args: SubscriptionGroupFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SubscriptionGroup | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "SubscriptionGroup",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => SubscriptionGroup)
  @nestAccessControl.UseRoles({
    resource: "SubscriptionGroup",
    action: "create",
    possession: "any",
  })
  async createSubscriptionGroup(
    @graphql.Args() args: CreateSubscriptionGroupArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SubscriptionGroup> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "SubscriptionGroup",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SubscriptionGroup"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => SubscriptionGroup)
  @nestAccessControl.UseRoles({
    resource: "SubscriptionGroup",
    action: "update",
    possession: "any",
  })
  async updateSubscriptionGroup(
    @graphql.Args() args: UpdateSubscriptionGroupArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SubscriptionGroup | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "SubscriptionGroup",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SubscriptionGroup"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SubscriptionGroup)
  @nestAccessControl.UseRoles({
    resource: "SubscriptionGroup",
    action: "delete",
    possession: "any",
  })
  async deleteSubscriptionGroup(
    @graphql.Args() args: DeleteSubscriptionGroupArgs
  ): Promise<SubscriptionGroup | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Plan])
  @nestAccessControl.UseRoles({
    resource: "SubscriptionGroup",
    action: "read",
    possession: "any",
  })
  async plans(
    @graphql.Parent() parent: SubscriptionGroup,
    @graphql.Args() args: PlanFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Plan[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Plan",
    });
    const results = await this.service.findPlans(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
